import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

public class App {
    public static void main(String[] args) throws Exception {
        JFrame f= new JFrame();
        JTextField nameField;
        JTextArea addressArea;
        JTextField emailField;
        JRadioButton maleButton;
        JRadioButton femaleButton;
        JComboBox<String> countryComboBox;
        JCheckBox hobbyReading;
        JCheckBox hobbyTravelling;
        JCheckBox hobbySports;
        JButton submitButton;
        f.setTitle("User Form");
        JLabel nameLabel = new JLabel("Name: ");
         nameLabel.setBounds(20,20,100,25);
        nameField=new JTextField();
        nameField.setBounds(140,20,200,25);
        f.add(nameLabel);
        f.add(nameField); 
        JLabel addressLabel=new JLabel("Address:");
        addressLabel.setBounds(20,60,100,25);
        addressArea = new JTextArea();
        addressArea.setBounds(140, 60, 200, 75);
        f.add(addressLabel);
        f.add(addressArea);
        JLabel emailLabel=new JLabel("Email:");
        emailLabel.setBounds(20, 150, 100, 25);
        emailField=new JTextField();
        emailField.setBounds(140, 150, 200, 25);
        f.add(emailLabel);
        f.add(emailField);
       
        JLabel genderLabel = new JLabel("Gender");
        genderLabel.setBounds(20, 190, 100, 25);
        maleButton =new JRadioButton("Male");
        maleButton.setBounds(140, 190, 100, 25);
        femaleButton= new JRadioButton("Female");
        femaleButton.setBounds(240, 190, 100, 25);
        JLabel countryLabel= new JLabel("Country");
        countryLabel.setBounds(20, 230, 0100, 25);
        String[] countries ={"USA","Canada","UK","Australia","Other"};
        countryComboBox = new JComboBox<>(countries);
        countryComboBox.setBounds(140, 230, 200, 25);
        f.add( countryLabel);
        f.add(countryComboBox);
        f.add(genderLabel);
        f.add(maleButton);
        f.add(femaleButton);
        JLabel hobbiesLabel = new JLabel("Hobbies");
        hobbiesLabel.setBounds(20,270,100,25);
        hobbyReading = new JCheckBox("Reading");
        hobbyReading.setBounds(140,270,100,25);
        hobbyTravelling = new JCheckBox("Travelling");
        hobbyTravelling.setBounds(140,300,100,25);
        hobbySports = new JCheckBox("Sports");
        hobbySports.setBounds(140,330,100,25);
        f.add(hobbiesLabel);
        f.add(hobbyReading);
        f.add(hobbyTravelling);
        f.add(hobbySports);
        submitButton=  new JButton("Submit");
        submitButton.setBounds(140, 380, 100, 25);
f.setSize(400,500);
f.setLayout(null);
f.setVisible(true);
    }
}
